on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests CI
    steps:
      - name: Run tests
        uses: ./
        run: sbt compile; scalafmtCheckAll; test