on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: ./